# Site settings
title: Yeats does not rhyme with Keats
email: pjdmatts@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  An notebook to act as a place to collect not totally useless things
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pjdmatts.github.io/" # the base hostname & protocol for your site
twitter_username: pjdmatts
github_username:  pjdmatts

# Build settings
markdown: kramdown
